
apiVersion: apps/v1
kind:  Deployment
metadata:
    name: myapp
    labels:
        app: myapp-test
        type: back-end
spec:
  selector:
    matchLabels:
      app: myapp-test
      tier: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp-test
        tier: myapp
    spec:
      containers:
          - name: myapp
            image: nitinmanoj/myapp

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: myapp-test
  ports:
  - protocol: TCP
    port: 5005
    targetPort: 5005
  type: NodePort
