apiVersion: v1
kind: Service
metadata:
  name: mydb
spec:
  ports:
  - port: 3306
  selector:
    app: mydb
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mydb
spec:
  selector:
    matchLabels:
      app: mydb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - image: nitinmanoj/mydb:latest
        name: mydb
        env:
            - name: MYSQL_DATABASE
              value: "SampleDB"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
        ports:
        - containerPort: 3306
          name: mydb
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
